# Generated by Django 2.1 on 2018-09-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobFinderWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='founded',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
