# Generated by Django 2.1 on 2018-09-15 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobFinderWeb', '0003_auto_20180915_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='pintrest',
            new_name='pinterest',
        ),
    ]
