# Generated by Django 2.1 on 2018-09-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobFinderWeb', '0012_auto_20180920_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumee',
            old_name='shordescription',
            new_name='shortdescription',
        ),
        migrations.AddField(
            model_name='resumee',
            name='website',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
