# Generated by Django 2.1 on 2018-09-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobFinderWeb', '0015_auto_20180920_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='datefrom',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='dateto',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
