# Generated by Django 2.1 on 2018-09-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobFinderWeb', '0017_auto_20180921_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumee',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
