# Generated by Django 2.1 on 2018-09-24 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobFinderWeb', '0020_auto_20180924_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resumee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JobFinderWeb.Resumee'),
        ),
    ]
