# Generated by Django 2.1 on 2018-09-26 06:33

import JobFinderWeb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobFinderWeb', '0023_auto_20180926_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=JobFinderWeb.models.upload_location, width_field='width_field'),
        ),
    ]
