# Generated by Django 2.1 on 2018-09-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobFinderWeb', '0024_auto_20180926_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='company', width_field='width_field'),
        ),
    ]
