# Generated by Django 2.1 on 2018-09-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobFinderWeb', '0025_auto_20180926_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='coverimage',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='coverimge', width_field='width_field'),
        ),
    ]
