# Generated by Django 2.1 on 2018-10-06 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobFinderWeb', '0028_auto_20180930_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JobFinderWeb.Seeker'),
        ),
        migrations.AlterField(
            model_name='application',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JobFinderWeb.Company'),
        ),
    ]
